# Generated by Django 4.0.3 on 2022-03-27 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('house', 'Casă'), ('car', 'Mașină'), ('work', 'Muncă'), ('others', 'Altele')], max_length=6)),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('deadline_date', models.DateTimeField()),
                ('reminder_time', models.CharField(choices=[(30, '30 de minute'), (60, '1 oră'), (180, '3 ore'), (720, '12 ore'), (1440, 'o zi'), (2880, '2 zile'), (10080, '7 zile')], max_length=10, verbose_name='Cu cât timp înainte doriți să primiți notificare?')),
                ('reminder_date', models.DateTimeField()),
                ('by_phone', models.BooleanField(verbose_name='Contact via phone')),
                ('by_email', models.BooleanField(verbose_name='Contact via email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
