# Generated by Django 4.0.3 on 2022-03-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
