# Generated by Django 4.0.3 on 2022-03-23 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
